import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";

const root = new URL("../", import.meta.url);

function readJson(path) {
  return JSON.parse(readFileSync(new URL(path, root), "utf8"));
}

test("the root exposes independent Web and Studio quality commands", () => {
  const manifest = readJson("package.json");

  assert.deepEqual(manifest.workspaces, ["apps/*", "packages/*"]);
  for (const script of [
    "build:web",
    "build:studio",
    "typegen",
    "typecheck",
    "check:generated",
    "check:dependencies",
    "check:secrets",
  ]) {
    assert.equal(typeof manifest.scripts[script], "string", `missing ${script} script`);
  }
});

test("runtime foundations are exact-pinned behind portfolio-owned packages", () => {
  const web = readJson("apps/web/package.json");
  const studio = readJson("apps/studio/package.json");
  const ui = readJson("packages/ui/package.json");

  assert.match(web.dependencies.next, /^\d+\.\d+\.\d+$/);
  assert.equal(web.dependencies["@portfolio/ui"], "*");
  assert.match(studio.dependencies.sanity, /^\d+\.\d+\.\d+$/);
  assert.equal(studio.dependencies["@portfolio/content"], "*");
  assert.equal(typeof studio.scripts.typegen, "string");
  assert.match(ui.dependencies["@base-ui/react"], /^\d+\.\d+\.\d+$/);

  const scaffoldButton = readFileSync(
    new URL("packages/ui/src/components/ui/button.tsx", root),
    "utf8",
  );
  const portfolioButton = readFileSync(new URL("packages/ui/src/button.tsx", root), "utf8");

  assert.match(scaffoldButton, /@base-ui\/react\/button/);
  assert.match(portfolioButton, /\.\/components\/ui\/button/);
  assert.match(portfolioButton, /export\s+(?:function|const)\s+Button/);

  const generatedTypes = readFileSync(
    new URL("packages/content/src/generated/sanity.types.ts", root),
    "utf8",
  );
  assert.match(generatedTypes, /generated by Sanity TypeGen/);
});

test("semantic TUI tokens cover the approved theme contract", () => {
  const tokens = readFileSync(new URL("packages/ui/src/tokens.css", root), "utf8");
  const requiredTokens = [
    "canvas",
    "surface",
    "surface-raised",
    "text-primary",
    "text-muted",
    "border",
    "border-strong",
    "focus",
    "accent",
    "accent-subtle",
    "link",
    "success",
    "warning",
    "danger",
    "selection",
  ];

  for (const token of requiredTokens) {
    assert.match(tokens, new RegExp(`--tui-${token}:`), `missing --tui-${token}`);
  }
});

test("prototype entry points and rejected assets are absent", () => {
  for (const path of [
    "index.html",
    "src/main.jsx",
    "src/styles.css",
    "src/assets/profile-photo-test.jpg",
  ]) {
    assert.equal(existsSync(join(root.pathname, path)), false, `${path} must not ship`);
  }

  const manifests = [
    readJson("package.json"),
    readJson("apps/web/package.json"),
    readJson("apps/studio/package.json"),
    readJson("packages/content/package.json"),
    readJson("packages/ui/package.json"),
  ];
  const directDependencies = manifests.flatMap((manifest) =>
    Object.keys({
      ...manifest.dependencies,
      ...manifest.devDependencies,
    }),
  );

  assert.equal(directDependencies.includes("vite"), false);
  for (const dependency of directDependencies) {
    assert.doesNotMatch(dependency, /atkinson-hyperlegible/i);
  }
});
